# Generated by Django 5.0.9 on 2024-12-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPS_Monitoring_App', '0003_estado_gps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estado_GPS',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='RastreoGPS',
        ),
    ]
